Lab 3: "HTML/CSS"
GritsH/itirod-webapp-auction pull request #2
Opened 2022-03-20 15:09 UTC by GritsH

https://gritsh.github.io/itirod-webapp-auction

Originally, i wanted to deply my project in heroku, but something went wrong, so here we are with my application on github pages

2022-03-28 11:39 UTC, katetushkan requested changes
Let's have a call if u are OK.

2022-03-28 11:39 UTC, katetushkan commented on css/addItem.css
> +    position: absolute;
why absolute?

2022-03-28 11:39 UTC, katetushkan commented on css/addItem.css
> +    position: absolute;
don't use percents for such a values

2022-03-28 11:39 UTC, katetushkan commented on css/addItem.css
> +    position: absolute;
same here. why absolute?

2022-03-28 12:11 UTC, GritsH commented
Yeah, let's have a call, just tell me when and where so i can be prepared 😰

пн, 28 мар. 2022 г. в 14:39, Katarina Tushinskaya ***@***.***
>:

> ***@***.**** requested changes on this pull request.
>
> Let's have a call if u are OK.
> ------------------------------
>
> In css/addItem.css
> <https://github.com/GritsH/itirod-webapp-auction/pull/2#discussion_r836330224>
> :
>
> > @@ -0,0 +1,59 @@
> +
> +.name-label {
> +    position: absolute;
>
> why absolute?
> ------------------------------
>
> In css/addItem.css
> <https://github.com/GritsH/itirod-webapp-auction/pull/2#discussion_r836332746>
> :
>
> > @@ -0,0 +1,59 @@
> +
> +.name-label {
> +    position: absolute;
> +    top: 20%;
> +    left: 5%;
> +}
> +
> +.item-name-input {
> +    position: absolute;
>
> same here. why absolute?
> ------------------------------
>
> In css/addItem.css
> <https://github.com/GritsH/itirod-webapp-auction/pull/2#discussion_r836332570>
> :
>
> > @@ -0,0 +1,59 @@
> +
> +.name-label {
> +    position: absolute;
>
> don't use percents for such a values
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GritsH/itirod-webapp-auction/pull/2#pullrequestreview-923005128>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOWF62WTUVTQHGBZEIGVUALVCGK6XANCNFSM5RFUCXJA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-28 12:21 UTC, katetushkan commented
U don't need to be prepared, I'll just explain u why absolute is not an option. March the 30th at 11-40 will be fine?

2022-04-05 11:47 UTC, katetushkan reviewed
Надо исправить то, что я написала и это будет на 8. Если хочешь больше - надо добавить стили  focus/ hover/ disabled на кнопки и линик.

2022-04-05 11:47 UTC, katetushkan commented on css/auctionRoom.css
> +.item-info_ {
Если хочешь чтобы было в центре, тогда используй text-align, а не маржин

2022-04-05 11:47 UTC, katetushkan commented on css/createLots.css
> +    height: 7%
лучше rem, a не %

2022-04-05 11:47 UTC, katetushkan commented on html/myAuctions.html
> +            <label class="lot-info">Current amount of participants: </label><br>
Если нет `<input>`, то не может быть и  `<label>`. Надо заменить на `<p>` например

2022-04-05 11:47 UTC, katetushkan commented on html/myAuctions.html
> +            <hr style="width: 95%">
вот это можно убрать, обернуть группу в контейнер, и сделать его flex

2022-04-05 13:08 UTC, GritsH commented
I’m doing some changes with styles you told me about right now 
If you can wait for about half an hour or so, you can check them 😰

> 5 апр. 2022 г., в 16:04, Katarina Tushinskaya ***@***.***> написал(а):
> 
> ﻿
> 8 Is enough?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

2022-04-11 13:14 UTC, katetushkan commented
Well, I'm sorry, but that's still an 8( u need look better in flex positioning and mobile version. It's working but it's not great. Let me know if u are okay with 8 or u wanna fix. 
<img width="516" alt="Screenshot 2022-04-11 at 15 13 12" src="https://user-images.githubusercontent.com/43992068/162746991-4aa98a5a-ab59-4e4d-9ea0-8737be7d5b2a.png">
.

2022-04-11 13:34 UTC, GritsH commented
Well, whatever 
I’ve missed deadline for the 4th work, so that doesn’t really matter 
I agree with 8

2022-04-12 11:30 UTC, katetushkan commented
> Well, whatever
> I’ve missed deadline for the 4th work, so that doesn’t really matter
> I agree with 8

`8` is urs, don't be upset about deadline, a lot of ur group mates haven't started a 1st work.

2022-04-12 11:37 UTC, merged